baseurl: https://blog.mattdaines.me
languageCode: en-gb
theme: hugo-theme-stack
paginate: 5
title: Matt Daines

# Change it to your Disqus shortname before using
disqusShortname: mattdaines

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2021
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 👨🏻‍💻
        subtitle: Azure security and infrastructure consultant. Welcome to my scrapbook!
        avatar:
            local: true
            src: img/avatar.jpeg

    article:
        math: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            site: MatthewDaines1
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: true
            src: img/avatar.jpeg

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params: 
            icon: home

        - identifier: about
          name: About
          url: /about/
          weight: -90
          params: 
            icon: user

        - identifier: archives
          name: Archives
          url: /archives/
          weight: -70
          params: 
            icon: archives

        - identifier: search
          name: Search
          url: /search/
          weight: -60
          params: 
            icon: search

    social:
        - identifier: twitter
          weight: 50
          name: Twitter
          url: https://twitter.com/MatthewDaines1
          params:
              icon: brand-twitter

        - identifier: linkedin
          weight: 60
          name: LinkedIn
          url: https://www.linkedin.com/in/matthew-daines/
          params:
              icon: brand-linkedin

        - identifier: github
          weight: 70
          name: GitHub
          url: https://github.com/MattDaines
          params:
              icon: brand-github

        - identifier: pluralsight
          weight: 80
          name: Pluralsight
          url: https://app.pluralsight.com/profile/matthew-daines
          params:
              icon: pluralsight

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
